// lib/api/errors.ts
import { ApiResponse, ResponseAction } from "./api-respone";

/**
 * @class ApiError
 * @extends {Error}
 * @description
 * Canonical error wrapper for all API responses in the EduAsas ecosystem. 
 * Converts standard or malformed backend error responses into a predictable, 
 * type-safe JavaScript Error object. 
 * 
 * This enables seamless error handling within TanStack Query mutations, 
 * async/await blocks, and UI notification systems.
 * 
 * @example
 * ```ts
 * try {
 *   await apiMutation("post", "/schools", data);
 * } catch (error) {
 *   if (isApiError(error)) {
 *     console.error(`[${error.statusCode}] ${error.errorCode}: ${error.message}`);
 *   }
 * }
 * ```
 */
export class ApiError extends Error {
  /** 
   * The status level of the response.
   * - "success": Request completed successfully.
   * - "error": Request failed or encountered a critical issue.
   * - "warning": Request completed with cautionary notes.
   */
  public status: "success" | "error" | "warning";

  /** 
   * The HTTP status code associated with the error response 
   * (e.g., 400, 401, 403, 422, 500).
   */
  public statusCode: number;

  /** 
   * Special instruction code sent by the backend instructing the frontend 
   * how to handle the side-effect (e.g., "RE_AUTHENTICATE", "KILL_CONTEXT", "REDIRECT", "NONE").
   */
  public action: ResponseAction;

  /** 
   * Optional payload data returned alongside the error response, 
   * often used for partial state recovery or debugging details.
   */
  public data: unknown;

  /** 
   * Machine-readable error code defined by the backend 
   * (e.g., "DUPLICATE_REGISTRATION", "INVALID_SUBDOMAIN", "SESSION_EXPIRED").
   * Ideal for targeted UI validation or specific field focus.
   */
  public errorCode?: string;

  /** 
   * Detailed validation errors (e.g., field-specific errors from Zod/NestJS validation) 
   * or nested error objects.
   */
  public errors?: unknown;

  /** 
   * ISO-8601 timestamp indicating exactly when the error was generated by the server or client.
   */
  public timestamp: string;

  /**
   * Creates an instance of ApiError.
   * 
   * @param {ApiResponse} apiResponse - The structured JSON response received from the backend API.
   * @param {number} [defaultStatusCode=500] - Fallback HTTP status code if the response lacks one.
   */
  constructor(apiResponse: ApiResponse, defaultStatusCode = 500) {
    super(apiResponse.message || "An unexpected error occurred");

    this.name = "ApiError";
    this.status = apiResponse.status || "error";
    this.statusCode = apiResponse.statusCode || defaultStatusCode;
    this.action = apiResponse.action || "NONE";
    this.data = apiResponse.data ?? null;
    this.errorCode = apiResponse.errorCode;
    this.errors = apiResponse.errors ?? null;
    
    // Fallback muhimu — inazuia timestamp kuwa undefined kama apiResponse haina.
    this.timestamp = apiResponse.timestamp || new Date().toISOString();

    // Inadumisha prototype chain sahihi kwenye TypeScript/Babel target environments
    Object.setPrototypeOf(this, ApiError.prototype);

    // V8-only (Chrome/Node.js) — inaondoa frame ya constructor kwenye stack trace 
    // ili stack ianze moja kwa moja pale `new ApiError(...)` ilipoitwa.
    if (typeof Error.captureStackTrace === "function") {
      Error.captureStackTrace(this, ApiError);
    }
  }
}

/**
 * Type guard function to safely narrow `unknown` catch blocks into an `ApiError`.
 * 
 * TypeScript strictly types `catch (error)` parameters as `unknown`. This utility 
 * allows developers to safely check and access custom properties like `error.statusCode`, 
 * `error.errorCode`, and `error.action` without TypeScript type errors.
 * 
 * @param {unknown} error - The caught error object in a try/catch block.
 * @returns {error is ApiError} True if the error is an instance of ApiError.
 * 
 * @example
 * ```ts
 * try {
 *   await submitRegistration();
 * } catch (error) {
 *   if (isApiError(error)) {
 *     // TypeScript knows `error` is ApiError here
 *     if (error.errorCode === "SUBDOMAIN_TAKEN") {
 *       setFieldError("subdomain", error.message);
 *     }
 *   }
 * }
 * ```
 */
export function isApiError(error: unknown): error is ApiError {
  return error instanceof ApiError;
}