name = "eduasas-frontend"
compatibility_date = "2026-09-07"

[site]
bucket = "dist"

[env.production]
vars = { VITE_API_URL = "https://api.eduasas.co.tz" }

[env.beta]
vars = { VITE_API_URL = "https://api.eduasas.co.tz" }